### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by qwibbler** [Lucas-Masaba/space-travelers#30]
https://github.com/Lucas-Masaba/space-travelers/projects
There are two people on our team. @Lucas-Masaba will be completing the rocket tasks while @qwibbler will be handling the missions tasks.

**Comment by Ghiftee** [comment]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽  @qwibbler @Lucas-Masaba 

Good job working on the project so far! 
✔️ Your PR contains the information of the people in your team.
✔️ All issues for student three has been closed.
However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/l1J3QMgxq4SS8EHXa/giphy.gif)

## Required Changes ♻️
- [x] There are currently 20 cards in your Kanban board but there should be 17, I can see that three cards are duplicated, kindly delete the duplicate cards.
- [x] The link to your project in this issue should be a link to your Kanban board which is this link```https://github.com/Lucas-Masaba/space-travelers/projects``` and not the one currently in your issue. Please update the link

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi @qwibbler @Lucas-Masaba, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/749155b89333c6d89386f5c98dd110e234a00f2aa1e864a5b3fecaf089aedb27/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f36664a31424d375232454252446e784b2f67697068792e676966)

Cheers and Happy coding!👏👏👏
